### ISSUE TITLE
profiles.data question

### ISSUE THREAD

**Issue by JuanDavidG1997** [Jonathan56/mosasik_ethereum_demo#1]
Hi,
I am interested in understanding on how you developed this simulation, because I would like to carry out some similar simulations.
I have a doubt about the way you give the profiles:
Each [date time] has 61 values when only 37 nodes exist. 
Could you please explain how this profile.datta file works?
Thank you!

**Comment by Jonathan56** [comment]
Hi, 
(it has been a while since I worked on it).
It seems that this is more a question for Mosaik, look at the `ResidentialLoads` model you might understand how the data is used afterward.

This is how I used PROFILE_FILE in demo.py
`houses = hhsim.ResidentialLoads(sim_start=START,
                                    profile_file=PROFILE_FILE,
                                    grid_name=GRID_NAME).children`

**Comment by JuanDavidG1997** [comment]
Thanks for your answer!
I've read the documentation I found, but I remain with some doubts. 
I would really appreciate if you could redirect me to some documentation you may have used or if you know the answer.
Do the 60 profiles correspond to "60  houses"?
Whats does num_hh mean? 
In the demand notebook you use only 10 nodes. Is there any reason for this? 
Sorry, but i'm really having a hard time understanding this file

**Comment by Jonathan56** [comment]
Hi Juan, 
profile.data is directly from the Mosaik project (it also seems like a weird format to me). I believe that asking questions to them would be more productive. Nonetheless, I believe that the 60 profiles correspond to 60 houses, and num_hh stands for numbers of households (at one node).

I only interact with 10 nodes, because only 10 nodes participate in the local energy market through the blockchain. I believe that the rest of the nodes continue to do their usual consumption (to be verified).

We wrote a paper out of this work :
[Co-simulation Framework for Blockchain Based Market Designs and Grid Simulations](https://doi.org/10.1109/PESGM.2018.8586124), Jonathan Coignard, Eric Munsing, Jason MacDonald, and Jonathan Mather; PES GM 2018.

I hope this is helpful.
Jonathan

**Comment by JuanDavidG1997** [comment]
Thank you once again Jonathan.
I am now over it and trying to run the simulations you did, but I'm having some trouble with market.json file. I think this file is created using truffle compile and truffle migrate --reset? 
Would you please give me a little detail on the OS you used at the time?
Thank you very much

**Comment by Jonathan56** [comment]
I used Mac OS, perhaps Truffle evolved since I last used it (https://www.trufflesuite.com/docs/truffle/overview)?
The important file is `Market.sol` somehow you need to compile it and deploy it on a blockchain.

**Comment by JuanDavidG1997** [comment]
Hi Jonathan.
I've managed to run truffle, but I have some doubts. The commands you state in the README are supposed to be run in the main directory right? I mean mosaik_ethereum_demo . Or is it supposed to be excecuted in ethereum dir?
I ask this cause when  I ran the commands I got a file named migrations.json instead of market.json and it doesn't work.
Sorry for bothering so much

**Comment by Jonathan56** [comment]
Hi Juan, 
I think the Ethereum command should be run in the Ethereum folder. I would advise getting the blockchain up and running without the MOSAIK stuff and vice versa before coupling both together. You should end up with a JSON file for each smart contract so it's normal to have a migrations.json, I believe?
I don't have the actual setup to re-run the experience easily so I can't update the README.

**Comment by JuanDavidG1997** [comment]
Thank you once again.
By now I've managed get Blockchain up and running, as you suggested. But now I've come to the issue that the truffle version I have installed works with solditity 0.5.6 which is newer that 0.4.4 as the .sol files you provide. 
That raises 2 questions for me. Is it possible to run everything using a newer version? (Erasing the version restriction line)
Do you happen to know the version of truffle you worked with?

**Comment by Jonathan56** [comment]
I don't know the truffle version I used. I don't remember the version of solidity being something important.
I think you should run everything with the new solidity version (perhaps some syntax error will show up ?).

**Comment by JuanDavidG1997** [comment]
Oh ok! I gave it a try and recieved some visibility issues. Something about neeeding to add some public declarations to the functions. Do you reckon this has anything to do with it?

**Comment by Jonathan56** [comment]
No clue. The only contract that I have added is `Market.sol`, feel free to reduce its complexity at first. Perhaps you can get the blockchain running with a dummy version of `Market.sol` and make your way to the full version step by step.
